### ISSUE TITLE
Won't work on Windows 11

### ISSUE THREAD

**Issue by Turstein** [m-nikolaidis/HPV16-Genotyper#1]
Hi!
I tried the Windows edition (but on Windows 11) and the exampleData works! But when trying other HPV16-fasta files (either reference alone (K02718.1) or combination of sequences) nothing happens. I am being sent to the screen where the progress bars are, but there is no progress. 

Do you know if there is a quick fix to this problem?

I also tried on ubuntu 20 (WSL2) and here I have some kind of installation trouble. A lot of unmet dependencies. 

Thank you :)

**Comment by Turstein** [comment]
Solved by itself. I had to choose output directory :)

**Comment by Marios-Nikolaidis** [comment]
Thank you very much for your comments. I will start working to fix those issues :)
